# Jekyll site settings
# ====================
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-CA"
title: "H. Martin Gillis"
# subtitle: ""
description: "Learning and developing technologies for artificial intelligence."
baseurl: ""
url: "https://nextdevai.github.io"
search: true
breadcrumbs: false

github: "[metadata]"
repository: "nextdevai/nextdevai.github.io"

masthead_title: "$ NextDevAI $"
# logo: "/assets/images/<filename>.png"

include:
  - _pages

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

author:
  name   : "H. Martin Gillis"
  avatar : "/assets/images/bio-photo.jpg"
  location: "Halifax, NS, Canada"
  bio    : "PhD Student at the Institute for Big Data Analytics."
  links:
    - label: "Dalhousie University"
      icon: "fas fa-fw fa-university"
      url: "https://www.dal.ca"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://bigdata.cs.dal.ca"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:martin.gillis@dal.ca"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nextdevai"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nextdevai"

markdown: "kramdown"
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: false
      show_date: true
      read_time: true
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author_profile: true

permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
timezone: "America/Halifax"

plugins:
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jemoji

category_archive:
  type: "liquid"
  path: "/categories/"
tag_archive:
  type: "liquid"
  path: "/tags/"

compress_html:
  clippings: "all"
  ignore:
    envs: "development"
